# Generated by Django 3.2.4 on 2021-06-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
